app/account/__init__.py
from flask import Blueprint

#The blueprint name will require when using url_for function.
account: Blueprint = Blueprint('account', __name__, template_folder='templates', static_folder='static',
                               url_prefix='/account')

# Attach registered routes to this blueprint
from app.account.routes import *

app/account/routes/__init__.py
# Register routes here
#Example:
# from app.auth.routes.routeFileName import routeName

from app.account.routes.profile import profile
from app.account.routes.dashboard import dashboard
from app.account.routes.study_dues import study_dues

app/account/routes/dashboard.py
from flask import render_template
from flask_login import login_required
from app.account import account
from app.account.services import dashboard_service


@account.route('/dashboard')
@login_required
def dashboard():
    mastered_chars_count = dashboard_service.mastered_chars_len
    vocabulary_count = dashboard_service.vocabulary_len
    return render_template('dashboard.html', title='Dashboard', mastered_chars_count=mastered_chars_count,
                           vocabulary_count=vocabulary_count)

app/account/routes/profile.py
from flask import render_template
from flask_login import current_user, login_required
# I did not choose:
# from app import account
# just to distinct between things directly coming from app package
# or from another package inside app package
from app.account import account


@account.route('/profile')
@login_required
def profile():
    return render_template('profile.html', title='Profile', user=current_user)

app/account/routes/study_dues.py
from flask import render_template
from flask_login import current_user, login_required
# I did not choose:
# from app import account
# just to distinct between things directly coming from app package
# or from another package inside app package
from app.account import account


@account.route('/study_dues')
@login_required
def study_dues():
    return render_template('review.html')

app/account/services/__init__.py
from app.account.repositories.dashboard_repository import DashboardRepository
from app.account.services.dashboard_service import DashboardService
from app import db

dashboard_service = DashboardService(DashboardRepository(db))

app/account/templates/modals/select_study_type.html
<div id="base-modal-container">
    <div v-if="isShowSelection" class="bottom-sheet-container">
        <div class="modal-sheet">
            {#            <div class="study-mode-selector">#}
            {#                <div class="time-selector">#}
            {#                    <button @click="selectType('Minutes')" :class="{ active: selectedType === 'Minutes' }">Minutes#}
            {#                    </button>#}
            {#                    <button @click="selectType('Words')" :class="{ active: selectedType === 'Words' }">Words</button>#}
            {#                    <div class="time-options">#}
            {#                        <button v-for="option in currentOptions" :key="option" @click="selectedValue = option"#}
            {#                                :class="{ active: selectedValue === option }">#}
            {#                            [[ option ]]#}
            {#                        </button>#}
            {#                    </div>#}
            {#                </div>#}
            {##}
            {#                <div v-if="!showCustomModes" class="study-modes">#}
            {#                    <div class="mode" @click="selectMode('Everyday')">#}
            {#                        <div class="icon">🌱</div>#}
            {#                        <h3>Everyday</h3>#}
            {#                        <p>Jump into a study session optimized for long-term growth.</p>#}
            {#                    </div>#}
            {#                    <div class="mode" @click="selectMode('Custom')">#}
            {#                        <div class="icon">⚙️</div>#}
            {#                        <h3>Custom</h3>#}
            {#                        <p>Explore a variety of custom study modes.</p>#}
            {#                    </div>#}
            {#                </div>#}
            {##}
            {#                <div v-if="showCustomModes" class="custom-modes-container">#}
            {#                    <button class="back-button" @click="showCustomModes = false">← Back</button>#}
            {#                    <div class="custom-modes">#}
            {#                        <div class="mode" v-for="mode in customModes" :key="mode.name"#}
            {#                             @click="selectCustomMode(mode.name)">#}
            {#                            <div class="icon">[[ mode.icon ]]</div>#}
            {#                            <h3>[[ mode.name ]]</h3>#}
            {#                            <p>[[ mode.description ]]</p>#}
            {#                        </div>#}
            {#                    </div>#}
            {#                </div>#}
            {##}
            {#                <p class="footer">Choose study limits and mode, or change your Settings.</p>#}
            {#            </div>#}

            {#            Animation Test#}
              <div class="study-mode-selector">
    <div class="time-selector">
      <div class="type-buttons">
        <button @click="selectType('Minutes')" :class="{ active: selectedType === 'Minutes' }">Minutes</button>
        <button @click="selectType('Words')" :class="{ active: selectedType === 'Words' }">Words</button>
      </div>
      <div class="selected-type">Selected: {{ selectedType }}</div>
      <div class="time-options">
        <button v-for="option in currentOptions" :key="option" @click="selectedValue = option" :class="{ active: selectedValue === option }">
          [[ option ]]
        </button>
      </div>
    </div>

    <div class="fade">
      <div v-if="!showCustomModes" class="study-modes">
        <div class="mode" @click="selectMode('Everyday')">
          <div class="icon">🌱</div>
          <a href="{{ url_for('account.study_dues') }}">Everyday</a>
          <p>Jump into a study session optimized for long-term growth.</p>
        </div>
        <div class="mode" @click="selectMode('Custom')">
          <div class="icon">⚙️</div>
          <h3>Custom</h3>
          <p>Explore a variety of custom study modes.</p>
        </div>
      </div>
    </div>

    <div class="slide-fade">
      <div v-if="showCustomModes" class="custom-modes-container">
        <button class="back-button" @click="showCustomModes = false">← Back</button>
        <div class="custom-modes">
          <div class="mode" v-for="mode in customModes" :key="mode.name" @click="selectCustomMode(mode.name)">
            <div class="icon">[[ mode.icon ]]</div>
            <h3>[[ mode.name ]]</h3>
            <p>[[ mode.description ]]</p>
          </div>
        </div>
      </div>
    </div>

    <p class="footer">Choose study limits and mode, or change your Settings.</p>
  </div>
            {#            End#}

        </div>
    </div>
</div>

app/account/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <h1>Profile</h1>
    <h1>{{ user.username }}</h1>
    <a href="{{ url_for('auth.signout') }}">Sign Out</a>
</body>
</html>