app/character/__init__.py
from flask import Blueprint

#The blueprint name will require when using url_for function.
character: Blueprint = Blueprint('character', __name__, template_folder='templates', static_folder='static',
                                 url_prefix='/character')

# Attach registered routes to this blueprint
from app.character.routes import *
from app.character.apis import *

app/character/apis/__init__.py
from app.character.apis.update_chars_detail import update_chars_detail
from app.character.apis.create_list import create_list
from app.character.apis.pin_list import pin_list
from app.character.apis.unpin_list import unpin_list
from app.character.apis.delete_list import delete_list
from app.character.apis.add_chars import add_chars

app/character/routes/__init__.py
from app.character.routes.lists import lists
from app.character.routes.sublists import sublists
from app.character.routes.reading_practice import reading_practice
from app.character.routes.study_never_studied import sns
from app.character.routes.recognition_practice import recognition_practice
from app.character.routes.add_chars_to_list import add_chars_to_list

app/character/routes/add_chars_to_list.py
from flask import render_template

from app.character import character
from app.character.services import lists_service


# Revise 1
# !! This codes also works well
@character.route('/add_chars_to_list/<int:list_id>', methods=['GET'])
def add_chars_to_list(list_id):
    return render_template('add_characters_to_list.html', list_id=list_id)

app/character/routes/lists.py
from flask import render_template

from app.character import character
from app.character.services import lists_service


# Revise 1
# !! This codes also works well
@character.route('/lists')
def lists():
    top_level_user_lists = lists_service.get_top_level_user_lists()
    top_level_premade_lists = lists_service.get_top_level_premade_lists()
    pinned_lists = lists_service.get_pinned_lists()

    return render_template('lists.html', user_lists=top_level_user_lists, premade_lists=top_level_premade_lists,
                           pinned_lists=pinned_lists)

app/character/routes/reading_practice.py
from random import choice

from flask import render_template

from app.character import character
from app.character.services import lists_service


@character.route('/reading_practice/<int:list_id>')
def reading_practice(list_id):
    characters = lists_service.get_characters_by_list_id(list_id)
    random_character = choice(characters)
    current_list = lists_service.get_list_by_id(list_id)
    return render_template('reading_practice.html',
                           title='Reading Practice', character=random_character,  list=current_list)

app/character/routes/recognition_practice.py
from flask import request, redirect, url_for, render_template, jsonify, json

from app.character import character
from app.character.services import lists_service


@character.route('/recognition_practice', methods=['POST'])
def recognition_practice():
    # option = request.form['option']
    # value = request.form['value']
    # Use the option and value here

    list_id = request.form.get('list_id')
    words_size = request.form.get('size')
    time_length = request.form.get('time')
    category = request.form.get('category')
    print('Category', category)
    practice_type = 'by_words_size'
    characters = []
    if words_size is not None:
        if category == 'ns':
            characters = [char.to_json() for char in
                          lists_service.get_never_studied_chars_of_list(list_id=list_id, limit=words_size)]
        if category == 'ws':
            characters = [char.to_json() for char in
                          lists_service.get_weak_chars_of_list(list_id=list_id, limit=words_size)]

            print('length', len(characters))
        if category == 'ss':
            characters = [char.to_json() for char in
                          lists_service.get_strong_chars_of_list(list_id=list_id, limit=words_size)]

    elif time_length is not None:
        practice_type = 'by_time_length'
        if category == 'ns':
            characters = [char.to_json() for char in
                          lists_service.get_never_studied_chars_of_list(list_id=list_id, limit=None)]
        if category == 'ws':
            characters = [char.to_json() for char in
                          lists_service.get_weak_chars_of_list(list_id=list_id, limit=None)]
        if category == 'ss':
            characters = [char.to_json() for char in
                          lists_service.get_strong_chars_of_list(list_id=list_id, limit=None)]
    print("Words Size: ", words_size)
    print("List ID: ", list_id)

    return render_template('recognition_practice.html', characters=characters, time_length=time_length,
                           practice_type=practice_type)

app/character/routes/study_never_studied.py
from random import choice

from flask import render_template, session

from app.character import character
from app.character.services import lists_service

never_studied_ten_chars = 'never_studied_ten_chars'
has_chars = 'has_chars'


class NevSd:
    def __init__(self, id: int, char: str, pinyin: str, meaning: str):
        self.id = id
        self.character = char
        self.pinyin = pinyin
        self.meaning = meaning

    def to_dict(self):
        return {'id': self.id, 'character': self.character, 'pinyin': self.pinyin, 'meaning': self.meaning}

    @staticmethod
    def from_dict(data):
        return NevSd(data['id'], data['character'], data['pinyin'], data['meaning'])


@character.route('/study/new/<int:list_id>')
def sns(list_id):
    session.clear()
    if 'never_studied_ten_chars' not in session:
        session['never_studied_ten_chars'] = []
    if 'has_chars' not in session:
        session['has_chars'] = False

    if not session[has_chars]:
        chars = [NevSd(char.id, char.character, char.pinyin, char.meaning) for char in
                 lists_service.get_ten_never_studied_chars(list_id)]
        print(chars[0].to_dict())
    if len(session[never_studied_ten_chars]) == 0 and session[has_chars] == False:
        session[never_studied_ten_chars] = [char_detail.to_dict() for char_detail in chars]
        session[has_chars] = True
    try:
        chars_temp = session[never_studied_ten_chars]
        char = chars_temp.pop()
        print('Char')
        print(char)
        lists_service.update_memory_strength([{'character_id': char['id'], 'is_correct': True}])
        session['never_studied_ten_chars'] = chars_temp
        # print(session['never_studied_ten_chars'])
    except IndexError:
        session.clear()
        return render_template('study_report.html', title='Session Report')
    return render_template('study_never_studied.html', title='Practice Never Studied', character=char, list_id=list_id)

app/character/routes/sublists.py
from flask import render_template
from flask_login import current_user

from app.character import character
from app.character.services import lists_service


@character.route('/lists/<int:list_id>')
def sublists(list_id):
    # Parent lists
    parents = lists_service.get_all_parent_lists(list_id)
    current_list = lists_service.get_list_by_id(list_id)
    never_learned_chars = lists_service.get_never_studied_chars_of_list(list_id, limit=None)
    strong_chars, weak_chars = lists_service.get_strong_weak_chars(list_id)
    if current_list is None:
        return 'List not found', 404
    child_lists = current_list.child_lists
    characters = current_list.characters
    pinned_child_lists = lists_service.get_pinned_sub_lists(parent_list_id=list_id)
    print('Pinned Child Lists: ', pinned_child_lists)
    return render_template('sublists.html', list=current_list, child_lists=child_lists,
                           characters=characters, parents=parents,
                           never_learned_chars=never_learned_chars,
                           strong_chars=strong_chars,
                           weak_chars=weak_chars,
                           pinned_lists=pinned_child_lists,
                           )

app/character/services/__init__.py
from app import db
from app.character.repositories.lists_repository import ListsRepository
from app.character.services.lists_service import ListsService

lists_service = ListsService(ListsRepository(db))

app/character/templates/add_characters_to_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script type="module" src="{{ url_for('.static', filename='js/addChars.js') }}"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <title>Document</title>
    <style>
        .modal-sheet {
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            max-width: 90%;

        }

        .modal-sheet .con-btns {
            display: flex;
            justify-content: space-between;
        }

        .bottom-sheet-container {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100vh;
            background-color: rgba(0, 0, 0, 0.5); /* Add a dark background to block clicks */
            z-index: 1000; /* Make sure the modal sheet is on top of everything */
            overflow-y: auto; /* Add this to make the modal sheet cover the whole page */
            overflow-x: hidden; /* Add this to prevent horizontal scrolling */
            display: flex;
            justify-content: center;
        }

        .modal-sheet {
            /* Make the modal sheet overlap the whole window */
            display: flex;
            justify-content: center;
            align-items: center;


        }

        .modal-sheet > div {
            /* Style the inner content of the modal sheet */
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }

        .selected {
            background-color: indianred !important; /* or any other color you prefer */
        }
    </style>
</head>

<body>

<div id="app">
    {% include 'modals/chars_addition_report.html' %}
    <label>
        <textarea v-model="text" style="width: 100%" rows="20"></textarea>
    </label>
    {{ list_id }}

    <span v-if="errorMsg">[[errorMsg]]</span>
    <div v-if="isAdding">
        <span v-if="isAdding">Processing</span>
    </div>
    <button v-else @click="()=>submitText('{{ list_id }}')">Add</button>
</div>
</body>
</html>

app/character/templates/macros.html
{% macro list_lists(lists, list_path) %}
  <ul>
  {% for list in lists %}
    <li><a href="{{ url_for('character.character_list', list_path=list_path + '/' + list.name) }}">{{ list.name }}</a>
    {% if list.child_lists %}
      {{ list_lists(list.child_lists, list_path + '/' + list.name) }}
    {% elif list.characters %}
      <h2>{{ list_path }}/{{ list.name }}</h2>
      <ul>
      {% for character in list.characters %}
        <li>{{ character.character }} ({{ character.pinyin }})</li>
      {% endfor %}
      </ul>
    {% endif %}
    </li>
  {% endfor %}
  </ul>
{% endmacro %}

app/character/templates/parts/char_lists_part.html
{% for char_list in lists %}
    <div class="list-card">
        <a href="{{ url_for('character.sublists', list_id=char_list.id) }}"><pre style="font-family: 'Open Sans', sans-serif;margin: 0">{{ char_list.name }}</pre></a>
        <div class="action-buttons">
            {% if char_list in pinned_lists %}
                <button @click="()=>unpinList('{{char_list.id}}')">Unpin</button>
                {% else %}
                <button @click="()=>pinList('{{char_list.id}}')">Pin</button>
            {% endif %}
            {% if not char_list.is_admin_created and characters | length == 0 %}
                <button @click="()=>showEditModal('{{ char_list.name }}', '{{ char_list.id }}')">&#128393</button>
                <button @click="()=> showDeleteModal('{{ char_list.name }}', '{{ char_list.id }}')">&#10008</button>
            {% endif %}
        </div>
    </div>
{% endfor %}

app/character/templates/reading_practice.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <style>
        body {
            background: #34495e;
            color: #ece6e6;
            margin: 0;
        }

        .hidden {
            visibility: hidden;
        }

        .card {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: space-around;

            padding: 20px;
            margin: 20px;
            max-width: 600px;
            transition: 0.3s;

        }

        .card-header {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
        }

        .card-header h1 {
            font-size: 2em;
            text-align: center;
        }

        .card-header button {
            margin-top: 10px;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            background-color: #008CBA;
            color: white;
            cursor: pointer;
        }

        .card-body {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
            text-align: center;
        }

        /* .card-body {
            margin: 8px;
        } */

        a {
            color: whitesmoke;
        }

        .know-not-confirmation {
            position: fixed;
            bottom: 0;
        }

        .card-body {

            width: 100%;
            display: flex;
            text-align: center;
            position: absolute;
            direction: column;
            justify-content: center;
            top: 30%;
        }

        .satire {
            width: 100%;
            display: flex;
            text-align: center;
            position: absolute;
            direction: column;
            vertical-align: middle;
            justify-content: center;
            top: 30%;
        }

        .satire p {
            font-size: 1.2em;
        }

        .know-not-confirmation {
            width: 100%;
            margin: 0;

        }

        .know-not-confirmation center button {
            width: 90%;
            border: none;
            border-radius: 5px;
            background: rgba(3, 230, 199, 0.76);
            color: whitesmoke;
            margin: 5px;
            padding: 12px;
            font-size: 1.2em;
        }

        .know-not-confirmation center button :hover {
            background: rgba(105, 121, 119, 0.96);
        }




        .ac-btns {

            display: flex;
            justify-content: space-between;
            width: 100%;
        }

        .ac-btns button {
            background: rgba(3, 230, 199, 0.76);
            border: none;
            margin: 5px;
            padding: 12px;
            border-radius: 5px;
            color: whitesmoke;
            font-size: 1.2em;
        }

        #navbar {
            position: sticky;
            top: 0;
            background-color: #3b5998;
            padding: 10px;
            z-index: 1;
            display: flex;
            justify-content: flex-end;

        }

        #navbar a {
            border-radius: 5px;
            background: #007bff3b;
            color: white;
            padding: 8px;
            margin-right: 1px;
            text-decoration: none;

        }
    </style>
</head>

<body>


    <!--  -->
{#    {% if error_msg %}#}
{#    <center>#}
{#        <h2>You first need to add characters here to practice!</h2>#}
{#    </center>#}
{#    {% else %}#}

    <div id="navbar">
        <a href="{{url_for('character.sublists', list_id=list.id)}}">Go Back</a>
    </div>


    <hr size="5px" style="border: none;">

    <div class="card-header">
        <div class="card">
            <div style="font-size: 5em;">{{character.character}}</div>

        </div>
    </div>
    <div class="card-body">

        <div class="hidden"> {{character.pinyin}}</div>
        <div style="font-size: 1.4em;" class="pinyin hidden"><span style="color: aquamarine;">Pinyin:</span>
            {{character.pinyin}}</div>
{#        <div style="font-size: 1.4em;" class="meaning hidden"><span style="color: aquamarine;">Meaning:</span>#}
{#            {{character.meaning}}</div>#}
{#        <div style="font-size: 1.4em;" class="hsk-level hidden"><span style="color: aquamarine;">HSK#}
{#                Level:</span>#}
{#            {{character.hsk_level}}#}
{#        </div>#}
    </div>


{#    <div class="satire">#}
{#        <p>#}
{#            {% if character.is_known %}#}
{#            You should know this character 😏#}
{#            {% else %}#}
{#            You may not know this character 🥲#}
{#            {% endif %}#}
{#        </p>#}
{#    </div>#}

    <div class="know-not-confirmation">
        <div class="ac-btns">

            <div>

{#                <form action="/update_data/{{character.id}}" method="post">#}
                <form action="#">
                    <input type="checkbox" id="known_{{character.id}}" name="known" value="on" hidden>
                    <button type="submit" value="I don't know"> I don't know</button>
                </form>
            </div>
            <div>

                <button id="show">Show</button>
            </div>
            <div>

{#                <form action="/update_data/{{character.id}}" method="post">#}
                <form action="#">

                    <input type="checkbox" id="known_{{character.id}}" name="known" value="on" hidden checked>
                    <button type="submit" value="I think I know"> I think I known </button>
                </form>
            </div>
        </div>


        <center><button onclick="reloadPage()">Skim
                Through</button></center>
    </div>
{#    {% endif %}#}
    <script>
        const showButton = document.getElementById('show');
        {#const satire = document.querySelector('.satire');#}
        const pinyin = document.querySelector('.pinyin');
        {#const meaning = document.querySelector('.meaning');#}
        {#const hskLevel = document.querySelector('.hsk-level');#}


        showButton.addEventListener('click', () => {

            {#satire.classList.toggle('hidden');#}
            pinyin.classList.toggle('hidden');

            {#meaning.classList.toggle('hidden');#}
            {#hskLevel.classList.toggle('hidden');#}
        });

        function reloadPage() {
            location.reload();
        }
    </script>

    <!-- <hr size="30" style="border: none;"> -->
</body>

</html>


{#Dummy Setup#}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>{{ title }}</title>#}
{#</head>#}
{#<body>#}
{#    <h1>I am reading practice</h1>#}
{#    {% for character in characters %}#}
{#        <span style="padding: 5px;margin: 3px;background: slategrey; color: #cccccc">{{ character.character }}</span>#}
{#    {% endfor %}#}
{#</body>#}
{#</html>#}

app/character/templates/study_report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <h1>Here is your summary</h1>
</body>
</html>

app/character/templates/sublists.html
{#This version also works well#}
<html lang="en-US">
<head>
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script type="module" src="{{ url_for('.static', filename='js/userCharLists.js') }}"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

    <title>List</title>
    <style>
        #strong span, #weak span, #never-sd span {
            background: blanchedalmond;
            padding: 5px;
            margin: 3px;
            border-radius: 5px;
            line-height: 35px;
            font-size: 1.3em;
        }

        .selected-button {
            background-color: #4CAF50;
            color: #fff;
            border: none;
            border-radius: 5px;
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
        }

        .selected-button:hover {
            background-color: #3e8e41;
        }

        .list-card {
            background: cadetblue;
            padding: 8px;
            margin: 10px;
            border-radius: 5px;
            display: flex;
            justify-content: space-between;
        }

        .list-card a {
            color: black;
            text-decoration: none;
        }

        .list-card a:hover {
            color: rebeccapurple;
        }

        .list-card .action-buttons button {
            margin-left: 2px;
        }

        .loading {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100vh;
            background-color: rgba(0, 0, 0, 0.5); /* Add a dark background to block clicks */
            z-index: 1000; /* Make sure the modal sheet is on top of everything */
            overflow-y: auto; /* Add this to make the modal sheet cover the whole page */
            overflow-x: hidden; /* Add this to prevent horizontal scrolling */
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .modal-sheet {
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            max-width: 480px;

        }

        .modal-sheet .con-btns {
            display: flex;
            justify-content: space-between;
        }

        .bottom-sheet-container {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100vh;
            background-color: rgba(0, 0, 0, 0.5); /* Add a dark background to block clicks */
            z-index: 1000; /* Make sure the modal sheet is on top of everything */
            overflow-y: auto; /* Add this to make the modal sheet cover the whole page */
            overflow-x: hidden; /* Add this to prevent horizontal scrolling */
            display: flex;
            justify-content: center;
        }

        .modal-sheet {
            /* Make the modal sheet overlap the whole window */
            display: flex;
            justify-content: center;
            align-items: center;


        }

        .modal-sheet > div {
            /* Style the inner content of the modal sheet */
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }
    </style>
</head>
<body>

<nav>
    <div>
        <span><a href="{{ url_for('character.lists') }}">All Lists</a></span> ->
        {% for parent in parents %}
            <span><a href="{{ url_for('character.sublists', list_id=parent.id) }}">{{ parent.name }}</a></span> ->
        {% endfor %}
        <span>{{ list.name }}</span>
    </div>
</nav>


<div id="app">
    {% include 'modals/modal.html' %}

    <h2>{{ list.name }}
        {% if not list.is_admin_created and characters | length == 0 and child_lists | length == 0 %}
            <button @click="showCreateListModal">Add List</button>
            <a href="{{ url_for('character.add_chars_to_list', list_id=list.id) }}">Add Characters</a>
        {% elif not list.is_admin_created and child_lists | length == 0 %}
            <a href="{{ url_for('character.add_chars_to_list', list_id=list.id) }}">Add Characters</a>
        {% else %}
            <button @click="showCreateListModal">Add List</button>
        {% endif %}

    </h2>

    {% with lists = child_lists %}
        {% include 'parts/char_lists_part.html' %}
    {% endwith %}
</div>

<div id="studyPopup">
    {% if characters|length != 0 %}
        {% if strong_chars|length != 0 %}
            <h2>Strong Words ({{ strong_chars|length }})</h2>
            <a href="{{ url_for('character.reading_practice', list_id=list.id) }}">Reading Practice</a>
            <button v-if="!showSSPopup" @click="openSSPopUp">Practice</button>
            <div style="position: relative">
                <div v-if="showSSPopup" class="popup">
                    <button @click="showSizes"
                            :class="{ 'selected-button': selectedOption === 'size' }">Words
                    </button>
                    <button @click="showTimes"
                            :class="{ 'selected-button': selectedOption === 'time' }">Times
                    </button>
                    <div v-if="showSizesList">
                        <button
                                v-for="size in sizes"
                                :key="size"
                                @click="selectOption('size', size)"
                                :class="{ 'selected-button': selectedOption === 'size' && selectedValue === size }"
                        >
                            [[ size ]]
                        </button>
                    </div>
                    <div v-if="showTimesList">
                        <button
                                v-for="time in times"
                                :key="time"
                                @click="selectOption('time', time)"
                                :class="{ 'selected-button' : selectedOption === 'time' && selectedValue === time }"
                        >
                            [[time]]
                        </button>
                    </div>
                    <button @click="start">Start</button>
                    <button @click="closeSSPopUp">Close</button>
                </div>
            </div>

            <div id="strong">
                {% for character in strong_chars %}
                    <span>{{ character.character }}</span>
                {% endfor %}
            </div>
        {% endif %}
        {% if weak_chars|length != 0 %}
            <h2>Weak Words ({{ weak_chars|length }})</h2>
            <a href="{{ url_for('character.reading_practice', list_id=list.id) }}">Reading Practice</a>
            <button v-if="!showWSPopup" @click="openWSPopUp">Practice</button>
            <div style="position: relative">
                <div v-if="showWSPopup" class="popup">
                    <button @click="showSizes"
                            :class="{ 'selected-button': selectedOption === 'size' }">Words
                    </button>
                    <button @click="showTimes"
                            :class="{ 'selected-button': selectedOption === 'time' }">Times
                    </button>
                    <div v-if="showSizesList">
                        <button
                                v-for="size in sizes"
                                :key="size"
                                @click="selectOption('size', size)"
                                :class="{ 'selected-button': selectedOption === 'size' && selectedValue === size }"
                        >
                            [[ size ]]
                        </button>
                    </div>
                    <div v-if="showTimesList">
                        <button
                                v-for="time in times"
                                :key="time"
                                @click="selectOption('time', time)"
                                :class="{ 'selected-button' : selectedOption === 'time' && selectedValue === time }"
                        >
                            [[time]]
                        </button>
                    </div>
                    <button @click="start">Start</button>
                    <button @click="closeWSPopUp">Close</button>
                </div>
            </div>

            <div id="weak">
                {% for character in weak_chars %}
                    <span>{{ character.character }} - {{ character.pinyin }}</span>
                {% endfor %}
            </div>
        {% endif %}

        {% if never_learned_chars|length != 0 %}
            <h2>Never Studied ({{ never_learned_chars|length }})</h2>
            <a href="{{ url_for('character.sns', list_id=list.id) }}">Learn 10 new words</a>
            <!-- Vue   -->
            <button v-if="!showNSPopup" @click="openNSPopUp">Practice</button>
            <div style="position: relative">
                <div v-if="showNSPopup" class="popup">
                    <button @click="showSizes"
                            :class="{ 'selected-button': selectedOption === 'size' }">Words
                    </button>
                    <button @click="showTimes"
                            :class="{ 'selected-button': selectedOption === 'time' }">Times
                    </button>
                    <div v-if="showSizesList">
                        <button
                                v-for="size in sizes"
                                :key="size"
                                @click="selectOption('size', size)"
                                :class="{ 'selected-button': selectedOption === 'size' && selectedValue === size }"
                        >
                            [[ size ]]
                        </button>
                    </div>
                    <div v-if="showTimesList">
                        <button
                                v-for="time in times"
                                :key="time"
                                @click="selectOption('time', time)"
                                :class="{ 'selected-button' : selectedOption === 'time' && selectedValue === time }"
                        >
                            [[time]]
                        </button>
                    </div>
                    <button @click="start">Start</button>
                    <button @click="closeNSPopUp">Close</button>
                </div>
            </div>
            <!--Vue End-->
            <div id="never-sd">
                {% for character in never_learned_chars %}
                    <span>{{ character.simplified }}</span>
                {% endfor %}
            </div>
        {% endif %}
    {% endif %}
</div>
<script>
    // console.log('{{list.id}}')
    let parentId = '{{ list.parent_list_id }}'
    console.log('Parent Id: ', parentId)
    let list_id = '{{ list.id }}'
    console.log('List Id: ', list_id)
</script>
{#<script type="module" src="{{ url_for('.static', filename='js/userCharLists.js') }}"></script>#}
<script type="module" src="{{ url_for('.static', filename='js/studyPopup.js') }}"></script>


</body>
</html>